### ISSUE TITLE
Not able to detect most technologies

### ISSUE THREAD

**Issue by hossamhossny** [AliasIO/Wappalyzer#1719]
I tested this on a Windows 10 machine:

`docker run --rm wappalyzer/cli https://wappalyzer.com`
```
[
  {
    "name": "Google Analytics",
    "confidence": "100",
    "version": "U",
    "icon": "Google Analytics.svg",
    "website": "http://google.com/analytics",
    "categories": [
      {
        "10": "Analytics"
      }
    ]
  },
  {
    "name": "Snap.svg",
    "confidence": "100",
    "version": "",
    "icon": "Snap.svg.png",
    "website": "http://snapsvg.io",
    "categories": [
      {
        "12": "JavaScript Frameworks"
      }
    ]
  }
]
```

So I re-tested on a Linux CentOS 7 latest machine:

`docker run --rm wappalyzer/cli https://wappalyzer.com
WARNING: IPv4 forwarding is disabled. Networking will not work.
Error: Timeout: did not get to load all resources on this page`

It complained about my docker containers not able to do networking so `echo 1 > /proc/sys/net/ipv4/ip_forward` and reran `docker run --rm wappalyzer/cli https://wappalyzer.com`

```
[
  {
    "name": "Google Analytics",
    "confidence": "100",
    "version": "U",
    "icon": "Google Analytics.svg",
    "website": "http://google.com/analytics",
    "categories": [
      {
        "10": "Analytics"
      }
    ]
  },
  {
    "name": "Snap.svg",
    "confidence": "100",
    "version": "",
    "icon": "Snap.svg.png",
    "website": "http://snapsvg.io",
    "categories": [
      {
        "12": "JavaScript Frameworks"
      }
    ]
  }
]
```

Same two technologies out of tons reported by Chrome extension.

**Comment by AlexByte** [comment]
For you 7 technology means tons?

**Comment by hossamhossny** [comment]
> For you 7 technology means tons?
For you, what you just wrote is considered a comment? I am sorry if I offended you complaining about a tool reporting technologies less than it should. You know already you should say something relevant or just refrain of commenting out?

**Comment by anonymez** [comment]
@hossamhossny might be using tons, but @AlexByte the fact that there is a difference between what the extension reports and what the docker or javascript library does. Is there any reason or misconfiguration to do so? I expected to have the same result from my extension and the available library. Can someone address me to the right issue or documentation? Thanks

**Comment by AliasIO** [comment]
The output should be identical. This is likely a bug.

**Comment by AlexByte** [comment]
You must build new image to find out that now in Node.js no technologies are detected.
user@pc:~$ sudo docker run wapp-cli https://wappalyzer.com
[]
```

**Comment by norwat** [comment]
I think i managed to fix this issue by applying the following patch to `wappalyzer.js`

`53a54
>
453,455c454,458
<           if ( header in headers && pattern.regex.test(headers[header]) ) {
<             this.addDetected(app, pattern, 'headers', headers[header], header);
<           }
---
>           headers._headers.forEach(h => {
>             if ( header == h[0] && pattern.regex.test(h[1]) ) {
>               this.addDetected(app, pattern, 'headers', headers[header], header);
>             }
>           });
`

However, the output using the npm driver does not show the implied apps, ie, if Wordpress then must be PHP. Im not sure if this is a bug or if its up to the script to make that association.

**Comment by AlexByte** [comment]
@norwat create pull request

**Comment by AliasIO** [comment]
Fixed in 1612c54d80c2251eb9173964e22d24ec332d579e.

**Comment by anonymez** [comment]
Thanks for the Fix @AliasIO , now I can get the same results as on my extension, GREAT!! I still have an issue using the index.js. My question is twofold :

1. Is there any other proper way to get information from a web page usign wapplyzer rather than index.js 

2. I run `index.js ttp://www.arcforums.com/forums/air/index.php` and the execution got stuck. I see the results, the json array is closed but  the program doesn't end. (should i open another issue?)

I'm using the most recent master you have, i've just pulled the code yesterday.

**Comment by AliasIO** [comment]
You don't have to use index.js, you can require driver.js in your own script and use that. Please open a new issue about the script not exiting.
