### ISSUE TITLE
Firefox hangs visiting AWS console

### ISSUE THREAD

**Issue by dqsully** [AliasIO/Wappalyzer#2054]
I am running Firefox Nightly 60.0a1 on KDE Neon (based on Ubuntu 16.04 Xenial) and everything has been great until today, when Wappalyzer apparently updated. Now every time I login to the AWS console one of the Firefox processes loops indefinitely at max cpu and the UI becomes unresponsive, forcing me to send a signal like SIGTERM directly to the hanging process. That is until I disable Wappalyzer in Firefox, then everything works just peachy again. I found this possibly related [bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1371594) about a similar problem with the Ghostery extension, if it helps anyone.

**Comment by AliasIO** [comment]
Thanks, it must be related to the change below. Should be fixed in the next update.

https://github.com/AliasIO/Wappalyzer/commit/4a711891fc4022ba8138c55c3ed44bbba32b59bb#diff-472301373a1b20de9d316bb2fc68a9ff

**Comment by nghitran** [comment]
I still encounter this issue with Wappalyzer v5.4.6 + Firefox 58.0.1 + MacOS. This issue also happens with JIRA, not only AWS Console

**Comment by gadcam** [comment]
@dqsully, @nghitran can you still reproduce this bug with Wappalyzer 5.4.11 ?
I pushed a fix for a lookalike issue which was merged in 27e1fa1.
If it did not fix I need a *reproducible* way to debug it : so at least a complete URL and maybe some preconditions.

**Comment by nghitran** [comment]
@gadcam the issue was fixed in version 5.4.11 for me.
