### ISSUE TITLE
Wappalyzer not working for bbc.com, wikipedia.org, airbnb.com, ebay.com (and more)

### ISSUE THREAD

**Issue by tracykennedy** [AliasIO/Wappalyzer#2530]
While using the NPM driver (wappalyzer version 5.5.4) I have been seeing a lot of timeouts. I ran into these while casually testing my script and it got me worried because I saw it happen so frequently.
My options are set to this:
    ```
const options = {
      debug: false,
      delay: 500,
      maxWait: 60000,
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36',
      recursive: false
    };

```
Here are some websites I **can not** seem to get wappalyzer to run successfully on:

- bbc.com
- wikipedia.org
- airbnb.com
- ebay.com

**Comment by leonelsr** [comment]
And it's worth mentioning that it ain't detecting React on https://web.whatsapp.com/ and fully not working on facebook.com

**Comment by AliasIO** [comment]
This should be fixed in the latest release.

**Comment by leonelsr** [comment]
> This should be fixed in the latest release.

Still not detecting React on https://web.whatsapp.com/ and fully not working on https://facebook.com
