### ISSUE TITLE
NPM driver example no longer works after release 5.6.0

### ISSUE THREAD

**Issue by anotherdevs** [AliasIO/Wappalyzer#2580]
**Do you want to request a *feature*, a *new application detection* or report a *bug*?**
Documentation out of date.

**Is your issue about WebExtension driver (Chrome & Firefox), the website, the NPM driver or the bookmarklet ?**
NPM driver.

**What is the current behavior ?**
Documentation out of date.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a demo of the problem.**
1) Copy example on https://github.com/AliasIO/Wappalyzer/tree/master/src/drivers/npm to editor and save as index.js
2) Run npm install wappalyzer
3) Run node index.js
4) It returns with error: TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type object

**What is the expected behavior ?**
Returns output about said website

**Which versions of Wappalyzer, and which browser / OS are affected by this issue ? Did this work in previous versions ?**
5.6.0

**Comment by doefler** [comment]
Found out you need to import a Browser and add it as the first parameter before the url parameter:
``` Javascript
const Browser = require('zombie');
Wappalyzer(Browser, url, options);
```

However I still get other errors too:

> UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'toLowerCase' of undefined

> DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

> [wappalyzer error] [driver] Uncaught exception: Cannot read property 'toLowerCase' of undefined

**Comment by juffardm** [comment]
I have the same issue. Did you solve it? :) Thanks!

**Comment by AliasIO** [comment]
Documentation has been updated here:

https://github.com/AliasIO/Wappalyzer/blob/master/src/drivers/npm/README.md

The correct line is:

```javascript
const Browser = require('./browsers/zombie');
```

**Comment by doefler** [comment]
@juffardm no haven't solved it yet.

@AliasIO the browsers folder isn't included in the NPM install, so I can include them like suggested.

I have these files:
<img width="214" alt="image 2018-12-15 at 12 38 22 am" src="https://user-images.githubusercontent.com/7951337/50035333-d5983480-0001-11e9-9b29-28558dcea9c8.png">

I use this version of Wappalyzer
 "wappalyzer": "^5.6.0",

**Comment by AliasIO** [comment]
I just pushed v5.6.1, please try that.

**Comment by juffardm** [comment]
Thanks a lot for your help! :D

**Comment by doefler** [comment]
Still not working @AliasIO .

Get this error:
```
module.js:487
    throw err;
    ^

Error: Cannot find module '../browser'
```

Can see in this file **node_modules/wappalyzer/browsers/zombie.js** that it tries to load a file that doens't exist:
```
const Browser = require('../browser');
```

Current folder:
<img width="221" alt="image 2018-12-15 at 3 20 25 pm" src="https://user-images.githubusercontent.com/7951337/50043937-fb165400-007c-11e9-873a-b4f47ec8c10e.png">

**Comment by AliasIO** [comment]
Added that one too, @doefler. Try v5.6.2.

**Comment by doefler** [comment]
@AliasIO It works now 👍 😄 
Thanks for the help.

Btw can I get access to the HTML/DOM from the browser instance initiated by Wappalyzer?
Would like to do some JS evaluation of the DOM like:
```
links = document.querySelectorAll('a')
```

**Comment by AliasIO** [comment]
@doefler I added events in v5.6.3, so you can do this:

```javascript
const wappalyzer = new Wappalyzer(Browser, url, options);

wappalyzer.on('visit', params => {
  const { browser, pageUrl } = params;

  // browser.document
});
```

**Comment by doefler** [comment]
@AliasIO amazing 😄 
Works beautifully. Thank you.

Do you know if the Zombie browser supports export of a HAR file. 
So you could analyze the website asset loading tree? Would be cool.
