### ISSUE TITLE
Cannot read property 'browser' of undefined (latest version)

### ISSUE THREAD

**Issue by ahmedsherif** [AliasIO/wappalyzer#3146]
**Platform**
MacOS
* NPM

**Describe the bug**
Cannot read property 'browser' of undefined

**To Reproduce**
Steps to reproduce the behaviour:
1. I only copied the code for the parallel scans from here:  https://www.npmjs.com/package/wappalyzer

2. I saved it to a file and only run the 'nodejs wpp.js' 
3. See error

`(node:71334) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'browser' of undefined
    at new Wappalyzer (/private/tmp/node_modules/wappalyzer/index.js:5:39)
    at /private/tmp/file.js:6:28
    at Object.<anonymous> (/private/tmp/file.js:24:3)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
(node:71334) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:71334) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Expected behaviour**
JSON response containing the technology for each website.

**Comment by AliasIO** [comment]
Fixed in v6.0.4.

**Comment by AliasIO** [comment]
This should no longer be an issue in v6.0.6.

**Comment by zcaceres** [comment]
I am on 6.0.12 (the latest on npm) and still have this problem.

**Comment by AliasIO** [comment]
@zcaceres Can you show me to full trace?

**Comment by zcaceres** [comment]
Will try to repro, almost same trace I'd say as the one listed above.
