### ISSUE TITLE
WebExtension icon should be of the main technology used to create the website

### ISSUE THREAD

**Issue by ShayKorin** [AliasIO/wappalyzer#3251]
**Is your feature request related to a problem? Please describe.**
Not sure if that's a bug or by design, but the Google Chrome extension icon  is currently showing the logo of the first technology in the technology list, which is not always the main technology that was used to create the site.
Sometimes it's one of the Analytics or Widgets technologies, for example.

**Describe the solution you'd like**
I would suggest the icon to reflect the main technology with which the site was created - the CMS / Page Builder / eCommerce categories

**Describe alternatives you've considered**
No alternative.

**Additional context**
No need.

**Comment by AliasIO** [comment]
The icon is picked based on the category, CMS is usually first. You can also pin a category in the popup. Can you show an example if that's not the case?

**Comment by ShayKorin** [comment]
I'm attaching 3 examples.
The sites were built using webflow, bigcommerce and shopify, but their icons are not the ones being shown.

![image](https://user-images.githubusercontent.com/10543787/88894525-aa9f3a80-d250-11ea-8d61-60dba07885bf.png)
![image](https://user-images.githubusercontent.com/10543787/88894551-b559cf80-d250-11ea-8cfa-7d5a21ecf859.png)
![image](https://user-images.githubusercontent.com/10543787/88894646-dde1c980-d250-11ea-80a9-db1a9cabbbb9.png)

**Comment by AliasIO** [comment]
Fixed in 5796b86ba91309b9b88721f24fed2c521339b768, thanks!

**Comment by ShayKorin** [comment]
@AliasIO - Thanks for the fix, the issue is mostly gone, but I still see a similar problem, check this for example:

![image](https://user-images.githubusercontent.com/10543787/89540185-60482b80-d805-11ea-847d-cf7734212c3a.png)
