### ISSUE TITLE
malformed JSON

### ISSUE THREAD

**Issue by Kikobeats** [AliasIO/wappalyzer#3897]
RequestError: Unexpected token ] in JSON at position 560518 in "https://raw.githack.com/aliasio/wappalyzer/master/src/technologies.json"

**Comment by AliasIO** [comment]
This was fixed, thanks!

**Comment by Kikobeats** [comment]
how is possible this is still happening even you have some scripts for linting and validating?

**Comment by AliasIO** [comment]
Because I'm sloppy and will often commit and push straight to master without validating. Validation happens automatically on pull requests and before builds, but not on push. If you're using the file in production I suggest using the latest tag rather than master.
