### ISSUE TITLE
Too much technologies shown on Chrome extension

### ISSUE THREAD

**Issue by rseon** [AliasIO/wappalyzer#4005]
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome)

**Describe the bug**
Seems that all technologies are shown in the extension :

![wappalyzer-bug](https://user-images.githubusercontent.com/1319497/121489752-ad240200-c9d4-11eb-8e9d-4f9ea8fe0cc1.jpg)
(from current page)

**Expected behavior**
Only used technologies must be shown

**Comment by Karbust** [comment]
I also noticed it sometimes carries around the same technologies through multiple websites. This only happened after the last update.

**Comment by nurbek91** [comment]
Hey guys , could u send links to websites  i'll take a look .

**Comment by Karbust** [comment]
Google.com: ![image](https://user-images.githubusercontent.com/20361229/121507870-f2e4c880-c9dc-11eb-85e7-feb7f1c4303d.png)

GitHub.com: ![image](https://user-images.githubusercontent.com/20361229/121507848-ed877e00-c9dc-11eb-9566-1940b909f821.png)

If I do a cache reset on the extension's options it holds until something bugs and starts carrying around technologies again.

**Comment by rseon** [comment]
I restarted Chrome but there is the same result (not the same as Karbust but those in my screenshot)

**Comment by uranderu** [comment]
This is also happening on Firefox. I spoke a friend that has the same issue, first happened today for both of us.

**Comment by AliasIO** [comment]
Does this issue return after clearing the detection cache in the extension settings?

**Comment by Karbust** [comment]
Not immediately, but ends up bugging again. Through out a day of visiting websites, it changes the "locked" detections, they don't stay always the same.

**Comment by AliasIO** [comment]
And it seems to be mixing the 'stuck' results with the correct results for the page, is that right?

**Comment by Karbust** [comment]
Yes, that's correct.

**Comment by AliasIO** [comment]
This never happens for me so it's difficult to debug. Is this still an issue? Have you tried reinstalling the extension completely?

**Comment by uranderu** [comment]
Yeah, I think it is gone for me now.  I didn't have to reinstall by the way.

**Comment by AliasIO** [comment]
Interesting. I wonder if the issue is related to leftover cache from the previous version, although clearing it should fix that. Please let me know if it regresses.

**Comment by Karbust** [comment]
> Interesting. I wonder if the issue is related to leftover cache from the previous version, although clearing it should fix that. Please let me know if it regresses.

It's back...

![image](https://user-images.githubusercontent.com/20361229/122351574-27f59b80-cf46-11eb-835b-843fb8eed95c.png)

**Comment by AliasIO** [comment]
I believe 40fe819220aa741a713cd74949ea7ea053747ba8 should fix this.

**Comment by Karbust** [comment]
> I believe [40fe819](https://github.com/AliasIO/wappalyzer/commit/40fe819220aa741a713cd74949ea7ea053747ba8) should fix this.

Well, now I can't even see any technology... When I enter on a new page, I need to refresh the page to show the technologies.

**Comment by AliasIO** [comment]
🤦 I'm pushing a stealth update, v6.7.7. It's difficult to debug as it doesn't seem to happen for me at all...

**Comment by Karbust** [comment]
> 🤦 I'm pushing a stealth update, v6.7.7. It's difficult to debug as it doesn't seem to happen for me at all...

Still happening on v6.7.6.

![image](https://user-images.githubusercontent.com/20361229/123553056-23fd2100-d771-11eb-901c-5d379183ac32.png)

**Comment by AliasIO** [comment]
On v6.7.6 or v6.7.7? The last one has been submitted but is pending approval, you can try installing it directly:

[webextension.zip](https://github.com/AliasIO/wappalyzer/files/6722292/webextension.zip)

**Comment by AliasIO** [comment]
v6.7.7 for Chrome is up now.

**Comment by Karbust** [comment]
> v6.7.7 for Chrome is up now.

I deleted the cache yesterday morning when I saw you pushed an update. Today I still have cached detections...

![image](https://user-images.githubusercontent.com/20361229/123919646-0ac8c000-d97d-11eb-89c9-1564731d59ae.png)

**Comment by nurbek91** [comment]
I installed the new version 6.7.7, and updated the Chrome browser itself. After that, the problem went away for me. At least I don't see such an error anymore.

**Comment by AliasIO** [comment]
> I deleted the cache yesterday morning when I saw you pushed an update. Today I still have cached detections...

@Karbust if you clear the cache again, do you get incorrect results after some time? Note that it's supposed to cache detections site-wide but it obviously shouldn't show results from others sites.

**Comment by Karbust** [comment]
> > I deleted the cache yesterday morning when I saw you pushed an update. Today I still have cached detections...
> 
> @Karbust if you clear the cache again, do you get incorrect results after some time? Note that it's supposed to cache detections site-wide but it obviously shouldn't show results from others sites.

I've cleared the cache again this morning, still happening (I'm on 6.7.7):
![image](https://user-images.githubusercontent.com/20361229/123964826-c4d72080-d9ab-11eb-8af2-c0b968fc3695.png)

It just get's "stuck" on some website, sometimes more than just one, the other day I had around 40 detections "stuck".

**Comment by AliasIO** [comment]
Included another fix in v6.7.10. 🤞

**Comment by Karbust** [comment]
> Included another fix in v6.7.10. 🤞

![image](https://user-images.githubusercontent.com/20361229/126357865-2f23f224-7ff1-4d4b-be78-9bace369bcf8.png)

![image](https://user-images.githubusercontent.com/20361229/126357879-ffbb2a91-1793-485c-a96b-29d9014ecaaa.png)

I had to uninstall the previous version (6.7.7) and use the unpacked version.

**Comment by AliasIO** [comment]
Another fix in v6.7.12. I'm hopeful. 🤞

**Comment by Karbust** [comment]
> Another fix in v6.7.12. I'm hopeful. 🤞

![image](https://user-images.githubusercontent.com/20361229/127750885-62a3a778-5d2a-4ff0-b35e-eca0a61229ec.png)

![image](https://user-images.githubusercontent.com/20361229/127750893-4d0d7bf7-dbb8-4edb-b0fd-7f4dff39cd72.png)

I don't know what to tell you... Still using the unpacked version, already cleared the cache multiple times.

This problem still doesn't happen with you? I don't have a way to test on other browsers, I'm running Vivaldi.

**Comment by AliasIO** [comment]
Thanks for your patience..! It happens to me exceedingly rarely so I'm debugging in the dark. I'm also getting very few reports on this, even though 1.5M people use the extension daily.

I'm pretty sure it's a timing issue. I noticed we were getting the tab URL _after_ the detections completed. If the tab URL changed in during this time, it could explain why some technologies get cached under the wrong URL.

It may depend on your browsing behaviour too. I usually open a new tab when going to a different website, rather than re-using an open tab. The only time I've seen this issue happen is when I go back and forth between sites in the same tab. Is this what you've noticed as well?

**Comment by Karbust** [comment]
> Thanks for your patience..! It happens to me exceedingly rarely so I'm debugging in the dark. I'm also getting very few reports on this, even though 1.5M people use the extension daily.
> 
> I'm pretty sure it's a timing issue. I noticed we were getting the tab URL _after_ the detections completed. If the tab URL changed in during this time, it could explain why some technologies get cached under the wrong URL.
> 
> It may depend on your browsing behaviour too. I usually open a new tab when going to a different website, rather than re-using an open tab. The only time I've seen this issue happen is when I go back and forth between sites in the same tab. Is this what you've noticed as well?

I usually open a new tab for everything, but on some rare occasions I reuse it. But even when I open a new one it happens, it doesn't happen immediately, takes a bit of "navigation".

Right now, I cleared the cache again after sending the print on the last reply, barely touched my computer, and it's bugged again... Usually IPBoard is almost always there, and sometimes Udemy's stack too.

If you need to add some code to help with the debugging let me now. This only started happening a few releases ago...

**Comment by AliasIO** [comment]
I've been trying to catch it happening by adding `console.log(url, detections)` in [`Driver.onDetect()`](https://github.com/AliasIO/wappalyzer/blob/master/src/drivers/webextension/js/driver.js#L481). At some point I noticed it reported the wrong technologies for a URL and after my last fix I didn't see it happen again. Basically I need to work out at what point it goes wrong.

If you can find specific steps to reproduce this on your end, that will help too.

**Comment by Karbust** [comment]
> I've been trying to catch it happening by adding `console.log(url, detections)` in [`Driver.onDetect()`](https://github.com/AliasIO/wappalyzer/blob/master/src/drivers/webextension/js/driver.js#L481). At some point I noticed it reported the wrong technologies for a URL and after my last fix I didn't see it happen again. Basically I need to work out at what point it goes wrong.
> 
> If you can find specific steps to reproduce this on your end, that will help too.

I don't know how to reproduce it, now I was just bouncing between (different tabs) this repo main page and https://developer.chrome.com/docs/extensions/mv3/tut_debugging/ (I never debugged a chrome extension) and I got this:
![image](https://user-images.githubusercontent.com/20361229/127753717-d5554844-d1e8-4072-93c6-67ca56147efb.png)



My console is like this: 
![image](https://user-images.githubusercontent.com/20361229/127753723-e4eda1fe-f90e-41a6-b0ed-c5fa8dc3f855.png)



On the detections I only saw up to 2 detections, mostly only 1 (at https://github.com/AliasIO/wappalyzer):
![image](https://user-images.githubusercontent.com/20361229/127753783-64a4ee4c-8376-4896-a90d-f7743927554c.png)



![image](https://user-images.githubusercontent.com/20361229/127753761-7d5b0944-6c6b-41e1-b5f8-29bac85a06ad.png)

**Comment by AliasIO** [comment]
Thanks, odd. I'll look into it more.

I hadn't noticed the `split` error in Chrome (I mainly use Firefox). I fixed it but it's probably not related.

**Comment by Karbust** [comment]
@AliasIO for now, 6.7.13 seems to be fixed, but I'll keep my eye on it to see if it regresses.

**Comment by Karbust** [comment]
@AliasIO it's still happening, not as usual, but I'm also using less the computer...

**Comment by rockeynebhwani** [comment]
@AliasIO  - I am seeing this on https://www.hfma.org.uk/. I See 186 technologies detected in Chrome extension and 13 different technologies under 'Ecommerce' category. 

![image](https://user-images.githubusercontent.com/1718757/131752333-6fd998df-2f7c-4b12-8ed3-0a96e8e5aad0.png)

Also, I didn't notice this via Chrome extension. I was querying something for Web Almanac in BigQuery and it came up in my list. This is the query I used -  

```
SELECT distinct url, count(*) as count
  FROM
    `httparchive.technologies.2021_07_01_mobile` 
where
 category = 'Ecommerce'
 group by url
 having count > 10
```

**Comment by Karbust** [comment]
> @AliasIO - I am seeing this on https://www.hfma.org.uk/. I See 186 technologies detected in Chrome extension and 13 different technologies under 'Ecommerce' category.
> 
> ![image](https://user-images.githubusercontent.com/1718757/131752333-6fd998df-2f7c-4b12-8ed3-0a96e8e5aad0.png)
> 
> Also, I didn't notice this via Chrome extension. I was querying something for Web Almanac in BigQuery and it came up in my list. This is the query I used -
> 
> ```
> SELECT distinct url, count(*) as count
>   FROM
>     `httparchive.technologies.2021_07_01_mobile` 
> where
>  category = 'Ecommerce'
>  group by url
>  having count > 10
> ```

That website is crazy, I just opened it and instantly got 181 technologies detected.

![image](https://user-images.githubusercontent.com/20361229/131752919-1dbd2dad-cf49-4467-b96c-40d3a091c0a2.png)

**Comment by rockeynebhwani** [comment]
@AliasIO - I ran this query and I am attaching some results from this query as I am able to replicate this issue with all these URLs. I removed extension and re-installed and I still see it

```
SELECT distinct url, count(*) as count
  FROM
    `httparchive.technologies.2021_07_01_mobile` 
 group by url
 having count > 70
```

<html>
<body>




1 | https://www.cameraland.nl/ | 180 |  
2 | https://www.santocongelado.com.br/ | 194 |  
3 | http://www.ptpl.altervista.org/ | 196 |  
4 | https://www.paolo-sonja.net/ | 193 |  
5 | https://farfallina.nl/ | 192 |  
6 | https://www.beautifeye.co.uk/ | 185 |  
7 | https://www.handdoekentoiletpapier.nl/ | 203 |  
8 | https://www.caddiscounter.com/ | 193 |  
9 | https://budget-sanitair.nl/ | 185 |  
10 | http://www.emanuelalenafisiatra.it/ | 188 |  
11 | https://www.theluxuryartmepra.com/ | 189 |  
12 | https://www.perfetta.it/ | 182 |  
13 | https://www.hdmikabelshop.nl/ | 181 |  
14 | https://www.247jeans.com/ | 183 |  
15 | https://www.drogarialiviero.com.br/ | 197 |  
16 | https://www.nail-academy-nicolle.nl/ | 188 |  
17 | https://www.homeinteriors.it/ | 190 |  
18 | https://www.massivholzplatten-shop.de/ | 188 |  
19 | https://www.shoppingdoscosmeticos.com.br/ | 190 |  
20 | https://www.thejewellers.com/ | 185 |  
21 | https://www.friseurscheren.info/ | 185 |  
22 | https://www.misterdesign.nl/ | 208 |  
23 | http://www.giannibelfiore.it/ | 193 |  
24 | https://www.ladyyard.jp/ | 186 |  
25 | https://www.calindogroup.it/ | 185 |  
26 | https://www.shoptoshape.com/ | 199 |  
27 | https://www.ilovecarousel.com/ | 206 |  
28 | https://www.alesandco.it/ | 188 |  
29 | https://www.l-otto.it/ | 176 |  
30 | https://verkkokauppa.tiivi.fi/ | 198 |  
31 | https://www.rehablab.eu/ | 180 |  
32 | https://www.gymcompany.it/ | 196 |  
33 | https://konstashop.fi/ | 186 |  
34 | https://www.hfma.org.uk/ | 185 |  
35 | http://www.renzobaldini.it/ | 186 |  
36 | https://www.butyotmet.pl/ | 187 |  
37 | https://www.exclusivebusinessgifts.com/ | 192 |  
38 | https://www.raytech.it/ | 209

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by AliasIO** [comment]
Something is going wrong in the [`getJs`](https://github.com/AliasIO/wappalyzer/blob/master/src/drivers/npm/driver.js#L58) function. I haven't figured out what exactly but I suspect those websites are overriding core APIs like `Array.prototype.reduce` or `String.prototype.split`, breaking our injected code. If I disable detection by JS it works fine.

**Comment by AliasIO** [comment]
I don't think this is the same as the caching issue.

**Comment by AliasIO** [comment]
I'm still not sure why but f2b1a4c15d09c0359a760cce6ce39b1b38d3d8fb fixes it.

@pmeenan you should adopt this change too.

**Comment by pmeenan** [comment]
WPT update is rolling out now, thanks

**Comment by AliasIO** [comment]
@Karbust are you still seeing this error from time to time? I haven't had any reports from anyone else recently.

**Comment by AliasIO** [comment]
[Fixed](https://github.com/AliasIO/wappalyzer/commit/fc57caa9892183d74c422fdfb736b4d4224fba31#diff-3a09560d3fab721a41189cfa740746e5f2ee1d7562d30fd862f17d4df9f517ecL568)! Finally. 

I found out that the cache was being written to storage incorrectly, saving the detections for the current URL to all websites. This issue would only happen if you close and reopen the browser, or reload the extension. I never close my browser so I was rarely seeing this issue happen.

This fix will be in v6.8.14.

**Comment by Karbust** [comment]
> [Fixed](https://github.com/AliasIO/wappalyzer/commit/fc57caa9892183d74c422fdfb736b4d4224fba31#diff-3a09560d3fab721a41189cfa740746e5f2ee1d7562d30fd862f17d4df9f517ecL568)! Finally.
> 
> I found out that the cache was being written to storage incorrectly, saving the detections for the current URL to all websites. This issue would only happen if you close and reopen the browser, or reload the extension. I never close my browser so I was rarely seeing this issue happen.
> 
> This fix will be in v6.8.14.

Word to mention the detection "Periodic" is being detected on every site.

About the cache, it hasn't happened in some days.

**Comment by rockeynebhwani** [comment]
@Karbust - Periodic issue has been taken care in https://github.com/AliasIO/wappalyzer/issues/4594
