### ISSUE TITLE
In some cases, detection works strange

### ISSUE THREAD

**Issue by zloirock** [AliasIO/wappalyzer#5625]
For example, `core-js`. In some cases, it's not detected

![image](https://user-images.githubusercontent.com/2213682/155124276-14668c68-f4fa-4306-9dcf-c56e8dee25a2.png)

or reported an incorrect version

![image](https://user-images.githubusercontent.com/2213682/155123984-c2b02a4e-6d9e-4870-81e4-d51853beca05.png)

The version of extension - the latest published (6.9.14), some of such problems I saw before, but on these sites it was detected properly.

**Comment by AliasIO** [comment]
Fixed in fb7eee340c57934ab33f2a348a65ea75594f7cce, thanks!

**Comment by zloirock** [comment]
@AliasIO hey, in the actual version (6.10.15), the second case still is not fixed.
